name: private-pypi-server

secrets:
  pypi_htpasswd:
    file: ./secrets/pypi_htpasswd

services:
  pypi:
    image: pypiserver/pypiserver:v2.1.1
    secrets:
      - pypi_htpasswd
    ports:
      - "8080:8080"
    volumes:
      - ./packages:/data/packages
    command: [
      # запускает сервер
      "run",
      # какие действия разрешены: установка, просмотр и загрузка пакетов
      "-a", "download, list, update",
      # путь к файлу с аутентификационными данными
      "-P", "/run/secrets/pypi_htpasswd",
      # используемый веб сервер gunicorn
      "--server", "gunicorn"
    ]
    restart: unless-stopped
