name: web_client_logger

secrets:
  mongo_root_username:
    file: ./secrets/mongo_root_username
  mongo_root_password:
    file: ./secrets/mongo_root_password

networks:
  private:
    internal: true
  public:

volumes:
  mongodata:

services:
  mongo:
    image: mongo:7.0-jammy
    secrets:
      - mongo_root_username
      - mongo_root_password
    networks:
      - private
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: ${MONGO_USERNAME_FILE}
      MONGO_INITDB_ROOT_PASSWORD_FILE: ${MONGO_PASSWORD_FILE}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

  app:
    build: ./src/app
    secrets:
      - mongo_root_username
      - mongo_root_password
    networks:
      - private
      - public
    ports:
      - "80:80"
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_USERNAME_FILE: ${MONGO_USERNAME_FILE}
      MONGO_PASSWORD_FILE: ${MONGO_PASSWORD_FILE}
      MONGO_DATABASE: ${MONGO_DATABASE}
    depends_on:
      - mongo
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    secrets:
      - mongo_root_username
      - mongo_root_password
    networks:
      - private
      - public
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}
      ME_CONFIG_MONGODB_ADMINUSERNAME_FILE: ${MONGO_USERNAME_FILE}
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: ${MONGO_PASSWORD_FILE}
      # Логин/Пароль для веб морды совпадает с логин/паролем админа (лучше так не делать =)
      ME_CONFIG_BASICAUTH_USERNAME_FILE: ${MONGO_USERNAME_FILE}
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: ${MONGO_PASSWORD_FILE}
    profiles:
      - debug
    depends_on:
      - mongo
    restart: unless-stopped
