name: web_client_logger

secrets:
  mongo_root_username:
    file: ./secrets/mongo_root_username
  mongo_root_password:
    file: ./secrets/mongo_root_password

networks:
  private:
    internal: true
  public:

volumes:
  mongodata:

services:
  mongo:
    image: mongo:7.0-jammy
    secrets:
      - mongo_root_username
      - mongo_root_password
    networks:
      - private
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
      MONGO_INITDB_DATABASE: test_database
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

  app:
    build: ./src/app
    secrets:
      - mongo_root_username
      - mongo_root_password
    networks:
      - private
      - public
    ports:
      - "80:80"
    environment:
      MONGO_HOST: mongo
      MONGO_USERNAME_FILE: /run/secrets/mongo_root_username
      MONGO_PASSWORD_FILE: /run/secrets/mongo_root_password
      MONGO_DATABASE: test_database
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./src/app:/var/www/html:ro

  mongo-express:
    image: mongo-express
    secrets:
      - mongo_root_username
      - mongo_root_password
    networks:
      - private
      - public
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME_FILE: /run/secrets/mongo_root_username
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo_root_password
      # Логин/Пароль для веб морды совпадает с логин/паролем админа (лучше так не делать =)
      ME_CONFIG_BASICAUTH_USERNAME_FILE: /run/secrets/mongo_root_username
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/mongo_root_password
    profiles:
      - debug
    depends_on:
      - mongo
    restart: unless-stopped
